### ISSUE TITLE
Educational Question: will this work with SceneGraph?

### ISSUE THREAD

**Issue by alinsan** [lvcabral/Donkey-Kong-Roku#39]
Will this source code/development approach work with Roku SceneGraph (and the latest version of the SDK)?

**Comment by lvcabral** [comment]
The Draw2D objects are not being deprecated, but you cant used both approaches at the same time, so specifically for Donkey Kong I will have to re-write the menu using Draw2D (like I did with Prince of Persia)

Said that, Roku team already said they are considering integrate Draw2D to SceneGraph in a future release, hopefully before the full deprecation of the SDK 1.0 components

**Comment by alinsan** [comment]
Thanks for the helpful answer! it looks like any of us interested in emulating this type of game will need to get started sooner rather than later... If we want to avoid getting confused dealing with the menu system, anyway...
