### ISSUE TITLE
Error when trying to Add Donkey Kong Roku Channel

### ISSUE THREAD

**Issue by jbl0ggs** [lvcabral/Donkey-Kong-Roku#41]
Error when trying to Add Donkey Kong Roku Channel using the following link...

https://my.roku.com/add/DonkeyKongPreview

"The channel code provided is not associated with a valid channel."

**Comment by lvcabral** [comment]
Nintendo requested Roku to remove the private channel, to have the channel now you need to download the release zip file and side load on your Roku.
